"use client";

import { useEvent } from "@/providers/event-provider";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { useQuery } from "@tanstack/react-query";
import { Download, Clock, CheckCircle2, FileArchive, FileImage, FileCode, Archive } from "lucide-react";

export default function QRDownloadsPage() {
  const { event } = useEvent();

  const { data: downloads, isLoading } = useQuery({
    queryKey: ["qr-downloads", event._id],
    queryFn: async () => {
      const res = await fetch(`/api/events/${event._id}/qr/downloads`);
      if (!res.ok) throw new Error("Failed to load downloads");
      return res.json();
    }
  });

  const getFormatIcon = (format: string) => {
    switch (format.toLowerCase()) {
      case "zip": return <Archive className="w-5 h-5 text-yellow-500" />;
      case "pdf": return <FileArchive className="w-5 h-5 text-red-500" />;
      case "svg": return <FileCode className="w-5 h-5 text-blue-500" />;
      case "png": return <FileImage className="w-5 h-5 text-green-500" />;
      default: return <Download className="w-5 h-5 text-slate-500" />;
    }
  };

  return (
    <div className="p-8 max-w-5xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Download History</h1>
        <p className="text-muted-foreground mt-1">Recent QR code exports from your workspace.</p>
      </div>

      <Card className="border-border/50 shadow-sm">
        <CardHeader className="bg-slate-900/20 border-b border-border/50">
          <CardTitle>Recent Exports</CardTitle>
          <CardDescription>The last 50 files generated by your team.</CardDescription>
        </CardHeader>
        <CardContent className="p-0">
          {isLoading ? (
            <div className="flex flex-col items-center justify-center py-20 text-muted-foreground">
              <Clock className="w-8 h-8 animate-pulse mb-4" />
              <p>Loading export history...</p>
            </div>
          ) : !downloads || downloads.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-20 text-muted-foreground border-2 border-dashed border-border/50 rounded-xl m-8">
              <Download className="w-8 h-8 mb-4 opacity-50" />
              <p>No exports generated yet.</p>
            </div>
          ) : (
            <div className="divide-y divide-border/50">
              {downloads.map((download: any) => (
                <div key={download._id} className="p-6 flex items-center justify-between hover:bg-slate-900/30 transition-colors">
                  <div className="flex items-center gap-4">
                    <div className="p-3 bg-slate-900 border border-slate-800 rounded-xl">
                      {getFormatIcon(download.format)}
                    </div>
                    <div>
                      <h3 className="font-semibold text-slate-200">{download.itemName}</h3>
                      <div className="flex items-center gap-2 mt-1 text-sm text-slate-400">
                        <span>{download.format.toUpperCase()}</span>
                        <span>•</span>
                        <span>{new Date(download.createdAt).toLocaleString()}</span>
                      </div>
                    </div>
                  </div>
                  
                  <div className="flex items-center gap-3">
                    <div className="flex items-center gap-2 text-sm text-emerald-400 bg-emerald-400/10 px-3 py-1 rounded-full">
                      <CheckCircle2 className="w-4 h-4" />
                      <span>Completed</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
