"use client";

import { useEvent } from "@/providers/event-provider";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Download, FileImage, Image as ImageIcon, FileText, Code } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { format } from "date-fns";
import { QRDownload } from "@/domain/types";
import { Badge } from "@/components/ui/badge";

const FileIcon = ({ format }: { format: string }) => {
  switch (format) {
    case "pdf": return <FileText className="w-5 h-5 text-red-500" />;
    case "svg": return <Code className="w-5 h-5 text-yellow-500" />;
    case "png": return <ImageIcon className="w-5 h-5 text-blue-500" />;
    default: return <FileImage className="w-5 h-5 text-green-500" />;
  }
};

export default function QRDownloadsPage() {
  const { event } = useEvent();

  const { data: downloads, isLoading } = useQuery<(QRDownload & { qrName: string })[]>({
    queryKey: ["qr-downloads", event._id],
    queryFn: async () => {
      const res = await fetch(`/api/events/${event._id}/qr/downloads`);
      if (!res.ok) throw new Error("Failed to fetch downloads");
      return res.json();
    }
  });

  return (
    <div className="p-8 max-w-5xl mx-auto space-y-8 h-full overflow-auto">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Download History</h1>
        <p className="text-muted-foreground mt-1">Recent QR code exports from your workspace.</p>
      </div>

      <Card className="border-border/50 shadow-sm">
        <CardHeader>
          <CardTitle>Recent Exports</CardTitle>
          <CardDescription>The last 50 files generated by your team.</CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="space-y-4">
              {[...Array(5)].map((_, i) => <div key={i} className="h-16 bg-muted animate-pulse rounded-lg"></div>)}
            </div>
          ) : downloads?.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground border rounded-lg border-dashed">
              <Download className="w-8 h-8 mx-auto opacity-50 mb-4" />
              <p>No exports generated yet.</p>
            </div>
          ) : (
            <div className="space-y-2">
              {downloads?.map((download) => (
                <div key={download._id as string} className="flex items-center justify-between p-4 border rounded-lg hover:bg-muted/50 transition-colors">
                  <div className="flex items-center gap-4">
                    <div className="p-2 bg-muted rounded-md">
                      <FileIcon format={download.format} />
                    </div>
                    <div>
                      <p className="font-medium text-sm">{download.qrName}</p>
                      <p className="text-xs text-muted-foreground">Exported {format(new Date(download.createdAt), "PPpp")}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-4">
                    <Badge variant="outline" className="uppercase">{download.format}</Badge>
                    <div className="text-xs text-muted-foreground hidden sm:block">
                      by {download.userId.substring(0, 8)}...
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
